"""DQN pre-training loop (paper Sec. V-C).

Pre-trains the DQNAgent on trajectories generated by the student simulator
environment, then saves the Q-network artifact to ml/artifacts/ for the
backend (apps.rl_feedback) to load for online action selection.
"""
import gymnasium as gym


def train_dqn(env: gym.Env, agent, config: dict):
    """Phase 6: run training episodes with epsilon-greedy exploration,
    experience replay, and target-network sync every 100 steps.
    Log reward curves for the convergence analysis (paper Sec. VIII)."""
    raise NotImplementedError("Phase 6")
