"""DQN pre-training loop (paper Sec. V-C).

Pre-trains the DQNAgent on trajectories generated by the student simulator
environment, then saves the Q-network artifact to ml/artifacts/ for the
backend (apps.rl_feedback) to load for online action selection.
"""
import json
import pathlib

import gymnasium as gym
import numpy as np

from .buffer import ReplayBuffer

ARTIFACTS_DIR = pathlib.Path(__file__).resolve().parent.parent.parent / "artifacts"


def train_dqn(env: gym.Env, agent, config: dict) -> dict:
    """Run training episodes with epsilon-greedy exploration, experience
    replay, and target-network sync every `target_update_steps` steps.
    Logs reward curves for the convergence analysis (paper Sec. VIII)."""
    config = config or {}
    episodes = int(config.get("max_episodes", 1000))
    steps_per_episode = int(config.get("steps_per_episode", 60))
    batch_size = int(config.get("batch_size", 64))
    eps_start = float(config.get("epsilon_start", 1.0))
    eps_end = float(config.get("epsilon_end", 0.05))
    eps_decay = int(config.get("epsilon_decay_steps", 20_000))
    log_every = int(config.get("log_every", 50))
    seed = config.get("random_state")

    buffer = ReplayBuffer(
        capacity=int(config.get("replay_buffer_size", 10_000)),
        state_dim=int(config.get("state_dim", 17)),
    )

    def epsilon(global_step: int) -> float:
        if eps_decay <= 0:
            return eps_end
        fraction = max(0.0, 1.0 - global_step / eps_decay)
        return eps_end + (eps_start - eps_end) * fraction

    episode_rewards: list[float] = []
    losses: list[float] = []
    global_step = 0

    for episode in range(1, episodes + 1):
        reset_seed = (None if seed is None else int(seed) + episode)
        state, _ = env.reset(seed=reset_seed)
        episode_reward = 0.0

        for _ in range(steps_per_episode):
            action = agent.select_action(state, epsilon(global_step))
            next_state, reward, terminated, truncated, _info = env.step(action)
            done = bool(terminated or truncated)
            buffer.push(state, action, reward, next_state, done)
            episode_reward += float(reward)

            if len(buffer) >= batch_size:
                losses.append(agent.train_step(buffer.sample(batch_size))["loss"])

            state = next_state
            global_step += 1
            if done:
                break

        episode_rewards.append(episode_reward)
        if log_every and episode % log_every == 0:
            tail = episode_rewards[-log_every:]
            mean_loss = float(np.mean(losses[-500:])) if losses else float("nan")
            print(
                f"[dqn] episode {episode}/{episodes} | mean reward {np.mean(tail):+.3f} "
                f"| eps {epsilon(global_step):.3f} | loss {mean_loss:.4f}"
            )

    artifact_path = pathlib.Path(config["artifact_path"]) if config.get("artifact_path") else ARTIFACTS_DIR / "dqn.pt"
    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    agent.save(str(artifact_path))

    tail_rewards = episode_rewards[-min(50, len(episode_rewards)):]
    metrics = {
        "episodes": episodes,
        "total_steps": global_step,
        "mean_reward_last50": float(np.mean(tail_rewards)) if tail_rewards else 0.0,
        "first_episode_reward": float(episode_rewards[0]) if episode_rewards else 0.0,
        "final_epsilon": epsilon(global_step),
        "mean_loss_last100": float(np.mean(losses[-100:])) if losses else None,
        "artifact": str(artifact_path),
    }
    # full curve for the pilot study's DQN-convergence analysis (Sec. VIII #3);
    # named after the artifact so short sweep runs don't clobber the real curve
    curve_path = artifact_path.parent / f"{artifact_path.stem}_training.json"
    curve_path.write_text(
        json.dumps(
            {
                "rewards": [round(float(r), 4) for r in episode_rewards],
                "episodes": episodes,
                "total_steps": global_step,
                "final_epsilon": metrics["final_epsilon"],
                "reward_weights": config.get("reward_weights"),
                "config": {
                    "gamma": config.get("gamma", 0.99),
                    "target_update_steps": config.get("target_update_steps", 100),
                    "batch_size": config.get("batch_size", 64),
                    "learning_rate": config.get("learning_rate", 0.0005),
                    "epsilon_decay_steps": config.get("epsilon_decay_steps", 20_000),
                },
            },
            indent=2,
        )
    )
    print(
        f"DQN trained: {episodes} episodes, {global_step} steps | "
        f"reward first {metrics['first_episode_reward']:+.3f} -> last-50 mean "
        f"{metrics['mean_reward_last50']:+.3f} | final eps {metrics['final_epsilon']:.3f}"
    )
    return metrics


def load_agent(config: dict | None = None, path: str | pathlib.Path | None = None):
    """Load the pre-trained DQNAgent for serving; FileNotFoundError until
    `make train-dqn` has run."""
    from .dqn import DQNAgent

    artifact = pathlib.Path(path) if path else ARTIFACTS_DIR / "dqn.pt"
    if not artifact.exists():
        raise FileNotFoundError(artifact)
    agent = DQNAgent(config or {})
    agent.load(str(artifact))
    return agent
